# Generated by Django 3.0.8 on 2022-04-30 14:41

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50, unique=True)),
                ('courseNumber', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('rank', models.IntegerField(choices=[(0, 'Freshman'), (1, 'Junior'), (2, 'Senior')], default=0)),
                ('userPic', models.ImageField(default='website/uploads/userPics/default_userPic.png', upload_to=users.models.User.upload_location)),
                ('isTeacher', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(blank=True, related_name='participants', to='users.Course')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
